<?php

namespace Database\Seeders;

use App\Models\GeneralData;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class GeneralDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('general_data')->insert([
            [
                "gData_id" => Str::random(9),
                "gData_componentId" => "rndComp01",
                "gData_tagNumber" => null,
                "gData_startingDate" => "1987-01-01",
                "gData_service" => null,
                "gData_manufacturedBy" => null,
                "gData_positionType" => null,
                "gData_shapeType" => null,
                "gData_geometryData" => null,
                "gData_code" => null,
                "gData_designPressureBar" => 11.3763,
                "gData_designPressurePsi" => 165.0019,
                "gData_designTemperatureC" => 232,
                "gData_designTemperatureR" => 185.6,
                "gData_designTemperatureF" => 449.6,
                "gData_designTemperatureK" => 505.15,
                "gData_operatingPressureBar" => 6.96,
                "gData_operatingPressurePsi" => 100.9478,
                "gData_operatingTemperatureC" => 55,
                "gData_operatingTemperatureR" => 44,
                "gData_operatingTemperatureF" => 131,
                "gData_operatingTemperatureK" => 328.15,
                "gData_dimensionLength" => null,
                "gData_dimensionWidth" => null,
                "gData_vesselVolumeLB" => null,
                "gData_vesselVolumeKG" => null,
                "gData_support" => null,
                "gData_jointEfficiency" => 1,
                "gData_yieldStrength" => 262000,
                "gData_tensileStrength" => 485000,
                "gData_corrosionAllowanceMM" => null,
                "gData_corrosionAllowanceInch" => null,
                "gData_yearBuilt" => null,
                "gData_material" => null,
                "gData_lastInspection" => "2019-03-20",
                "gData_nominalThicknessMM" => null,
                "gData_thickAfterInspMM" => null,
                "gData_outerDiameterMM" => null,
                "gData_outerDiameterInch" => null,
                "gData_allowableStressPsig" => "17499.9565",
                "gData_allowableStressBar" => "1206.58",
                "gData_allowableStressKpa" => "120658",
                "gData_efficiency" => null,
                "gData_shellCode" => null,
                "gData_shellMinimumThicknessMM" => "15.8",
                "gData_shellMinimumThicknessInch" => "0.622",
                "gData_shellCorrosionRateMM" => "0.0057",
                "gData_shellCorrosionRateInch" => "0.0002",
                "gData_shellTreqInch" => "0.5051",
                "gData_shellTreqMM" => "12.83",
                "gData_shellMAWP" => "202.4",
                "gData_headCode" => "ASME Section VIII Division 1",
                "gData_headMinimumThicknessMM" => "18.4",
                "gData_headMinimumThicknessInch" => "0.7244",
                "gData_headCorrosionRateMM" => "0.006",
                "gData_headCorrosionRateInch" => "0.0002",
                "gData_headTreqInch" => "0.5094",
                "gData_headTreqMM" => "12.94",
                "gData_headMAWP" => "209.967",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "gData_id" => Str::random(9),
                "gData_componentId" => "rndComp02",
                "gData_tagNumber" => null,
                "gData_startingDate" => null,
                "gData_service" => null,
                "gData_manufacturedBy" => null,
                "gData_positionType" => null,
                "gData_shapeType" => null,
                "gData_geometryData" => null,
                "gData_code" => null,
                "gData_designPressureBar" => null,
                "gData_designPressurePsi" => null,
                "gData_designTemperatureC" => null,
                "gData_designTemperatureR" => null,
                "gData_designTemperatureF" => null,
                "gData_designTemperatureK" => null,
                "gData_operatingPressureBar" => null,
                "gData_operatingPressurePsi" => null,
                "gData_operatingTemperatureC" => null,
                "gData_operatingTemperatureR" => null,
                "gData_operatingTemperatureF" => null,
                "gData_operatingTemperatureK" => null,
                "gData_dimensionLength" => null,
                "gData_dimensionWidth" => null,
                "gData_vesselVolumeLB" => null,
                "gData_vesselVolumeKG" => null,
                "gData_support" => null,
                "gData_jointEfficiency" => null,
                "gData_yieldStrength" => null,
                "gData_tensileStrength" => null,
                "gData_corrosionAllowanceMM" => null,
                "gData_corrosionAllowanceInch" => null,
                "gData_yearBuilt" => null,
                "gData_material" => null,
                "gData_lastInspection" => null,
                "gData_nominalThicknessMM" => null,
                "gData_thickAfterInspMM" => null,
                "gData_outerDiameterMM" => null,
                "gData_outerDiameterInch" => null,
                "gData_allowableStressPsig" => null,
                "gData_allowableStressBar" => null,
                "gData_allowableStressKpa" => null,
                "gData_efficiency" => null,
                "gData_shellCode" => null,
                "gData_shellMinimumThicknessMM" => null,
                "gData_shellMinimumThicknessInch" => null,
                "gData_shellCorrosionRateMM" => null,
                "gData_shellCorrosionRateInch" => null,
                "gData_shellTreqInch" => null,
                "gData_shellTreqMM" => null,
                "gData_shellMAWP" => null,
                "gData_headCode" => null,
                "gData_headMinimumThicknessMM" => null,
                "gData_headMinimumThicknessInch" => null,
                "gData_headCorrosionRateMM" => null,
                "gData_headCorrosionRateInch" => null,
                "gData_headTreqInch" => null,
                "gData_headTreqMM" => null,
                "gData_headMAWP" => null,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "gData_id" => Str::random(9),
                "gData_componentId" => "rndComp03",
                "gData_tagNumber" => null,
                "gData_startingDate" => null,
                "gData_service" => null,
                "gData_manufacturedBy" => null,
                "gData_positionType" => null,
                "gData_shapeType" => null,
                "gData_geometryData" => null,
                "gData_code" => null,
                "gData_designPressureBar" => null,
                "gData_designPressurePsi" => null,
                "gData_designTemperatureC" => null,
                "gData_designTemperatureR" => null,
                "gData_designTemperatureF" => null,
                "gData_designTemperatureK" => null,
                "gData_operatingPressureBar" => null,
                "gData_operatingPressurePsi" => null,
                "gData_operatingTemperatureC" => null,
                "gData_operatingTemperatureR" => null,
                "gData_operatingTemperatureF" => null,
                "gData_operatingTemperatureK" => null,
                "gData_dimensionLength" => null,
                "gData_dimensionWidth" => null,
                "gData_vesselVolumeLB" => null,
                "gData_vesselVolumeKG" => null,
                "gData_support" => null,
                "gData_jointEfficiency" => null,
                "gData_yieldStrength" => null,
                "gData_tensileStrength" => null,
                "gData_corrosionAllowanceMM" => null,
                "gData_corrosionAllowanceInch" => null,
                "gData_yearBuilt" => null,
                "gData_material" => null,
                "gData_lastInspection" => null,
                "gData_nominalThicknessMM" => null,
                "gData_thickAfterInspMM" => null,
                "gData_outerDiameterMM" => null,
                "gData_outerDiameterInch" => null,
                "gData_allowableStressPsig" => null,
                "gData_allowableStressBar" => null,
                "gData_allowableStressKpa" => null,
                "gData_efficiency" => null,
                "gData_shellCode" => null,
                "gData_shellMinimumThicknessMM" => null,
                "gData_shellMinimumThicknessInch" => null,
                "gData_shellCorrosionRateMM" => null,
                "gData_shellCorrosionRateInch" => null,
                "gData_shellTreqInch" => null,
                "gData_shellTreqMM" => null,
                "gData_shellMAWP" => null,
                "gData_headCode" => null,
                "gData_headMinimumThicknessMM" => null,
                "gData_headMinimumThicknessInch" => null,
                "gData_headCorrosionRateMM" => null,
                "gData_headCorrosionRateInch" => null,
                "gData_headTreqInch" => null,
                "gData_headTreqMM" => null,
                "gData_headMAWP" => null,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "gData_id" => Str::random(9),
                "gData_componentId" => "rndComp04",
                "gData_tagNumber" => null,
                "gData_startingDate" => null,
                "gData_service" => null,
                "gData_manufacturedBy" => null,
                "gData_positionType" => null,
                "gData_shapeType" => null,
                "gData_geometryData" => null,
                "gData_code" => null,
                "gData_designPressureBar" => null,
                "gData_designPressurePsi" => null,
                "gData_designTemperatureC" => null,
                "gData_designTemperatureR" => null,
                "gData_designTemperatureF" => null,
                "gData_designTemperatureK" => null,
                "gData_operatingPressureBar" => null,
                "gData_operatingPressurePsi" => null,
                "gData_operatingTemperatureC" => null,
                "gData_operatingTemperatureR" => null,
                "gData_operatingTemperatureF" => null,
                "gData_operatingTemperatureK" => null,
                "gData_dimensionLength" => null,
                "gData_dimensionWidth" => null,
                "gData_vesselVolumeLB" => null,
                "gData_vesselVolumeKG" => null,
                "gData_support" => null,
                "gData_jointEfficiency" => null,
                "gData_yieldStrength" => null,
                "gData_tensileStrength" => null,
                "gData_corrosionAllowanceMM" => null,
                "gData_corrosionAllowanceInch" => null,
                "gData_yearBuilt" => null,
                "gData_material" => null,
                "gData_lastInspection" => null,
                "gData_nominalThicknessMM" => null,
                "gData_thickAfterInspMM" => null,
                "gData_outerDiameterMM" => null,
                "gData_outerDiameterInch" => null,
                "gData_allowableStressPsig" => null,
                "gData_allowableStressBar" => null,
                "gData_allowableStressKpa" => null,
                "gData_efficiency" => null,
                "gData_shellCode" => null,
                "gData_shellMinimumThicknessMM" => null,
                "gData_shellMinimumThicknessInch" => null,
                "gData_shellCorrosionRateMM" => null,
                "gData_shellCorrosionRateInch" => null,
                "gData_shellTreqInch" => null,
                "gData_shellTreqMM" => null,
                "gData_shellMAWP" => null,
                "gData_headCode" => null,
                "gData_headMinimumThicknessMM" => null,
                "gData_headMinimumThicknessInch" => null,
                "gData_headCorrosionRateMM" => null,
                "gData_headCorrosionRateInch" => null,
                "gData_headTreqInch" => null,
                "gData_headTreqMM" => null,
                "gData_headMAWP" => null,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ]
        ]);
    }
}
