<?php

namespace App\DTO\GeneralData;

use App\Http\Requests\GeneralData\CreateGeneralDataRequest;
use Illuminate\Support\Str;

class InsertGeneralDataDTO
{
    public function __construct(
        public readonly string $gData_componentId,
        public readonly ?string $gData_tagNumber = null,
        public readonly ?string $gData_startingDate = null,
        public readonly ?string $gData_service = null,
        public readonly ?string $gData_manufacturedBy = null,
        public readonly ?string $gData_positionType = null,
        public readonly ?string $gData_shapeType = null,
        public readonly ?string $gData_geometryData = null,
        public readonly ?string $gData_code = null,
        public readonly ?string $gData_setPressurePsig = null,
        public readonly ?string $gData_reliefingTemperatureF = null,
        public readonly ?string $gData_allowableOverPress = null,
        public readonly ?string $gData_designPressureBar = null,
        public readonly ?string $gData_designPressurePsi = null,
        public readonly ?string $gData_designTemperatureC = null,
        public readonly ?string $gData_designTemperatureR = null,
        public readonly ?string $gData_designTemperatureF = null,
        public readonly ?string $gData_designTemperatureK = null,
        public readonly ?string $gData_operatingPressureBar = null,
        public readonly ?string $gData_operatingPressurePsi = null,
        public readonly ?string $gData_operatingTemperatureC = null,
        public readonly ?string $gData_operatingTemperatureR = null,
        public readonly ?string $gData_operatingTemperatureF = null,
        public readonly ?string $gData_operatingTemperatureK = null,
        public readonly ?string $gData_dimmension = null,
        public readonly ?string $gData_vesselVolumeLB = null,
        public readonly ?string $gData_vesselVolumeKG = null,
        public readonly ?string $gData_support = null,
        public readonly ?string $gData_jointEfficiency = null,
        public readonly ?string $gData_yieldStrength = null,
        public readonly ?string $gData_tensileStrength = null,
        public readonly ?string $gData_corrosionAllowanceMM = null,
        public readonly ?string $gData_corrosionAllowanceInch = null,
        public readonly ?string $gData_yearBuilt = null,
        public readonly ?string $gData_material = null,
        public readonly ?string $gData_lastInspection = null,
        public readonly ?string $gData_nominalThicknessMM = null,
        public readonly ?string $gData_thickAfterInspMM = null,
        public readonly ?string $gData_outerDiameterMM = null,
        public readonly ?string $gData_outerDiameterInch = null,
        public readonly ?string $gData_allowableStressPsig = null,
        public readonly ?string $gData_allowableStressBar = null,
        public readonly ?string $gData_allowableStressKpa = null,
        public readonly ?string $gData_efficiency = null,
        public readonly ?string $gData_shellCode = null,
        public readonly ?string $gData_shellMinimumThicknessMM = null,
        public readonly ?string $gData_shellMinimumThicknessInch = null,
        public readonly ?string $gData_shellCorrosionRateMM = null,
        public readonly ?string $gData_shellCorrosionRateInch = null,
        public readonly ?string $gData_shellTreqInch = null,
        public readonly ?string $gData_shellTreqMM = null,
        public readonly ?string $gData_shellMAWP = null,
        public readonly ?string $gData_headCode = null,
        public readonly ?string $gData_headMinimumThicknessMM = null,
        public readonly ?string $gData_headMinimumThicknessInch = null,
        public readonly ?string $gData_headCorrosionRateMM = null,
        public readonly ?string $gData_headCorrosionRateInch = null,
        public readonly ?string $gData_headTreqInch = null,
        public readonly ?string $gData_headTreqMM = null,
        public readonly ?string $gData_headMAWP = null,
    ) {
    }

    public static function fromRequest(CreateGeneralDataRequest $request): self
    {
        return new self(
            gData_componentId: $request->validated('gData_componentId'),
        );
    }

    public function build(): array
    {
        return [
            'gData_id' => Str::random(9),
            "gData_componentId" => $this->gData_componentId,
            "gData_tagNumber" => $this->gData_tagNumber,
            "gData_startingDate" => $this->gData_startingDate,
            "gData_service" => $this->gData_service,
            "gData_manufacturedBy" => $this->gData_manufacturedBy,
            "gData_positionType" => $this->gData_positionType,
            "gData_positionType" => $this->gData_positionType,
            "gData_shapeType" => $this->gData_shapeType,
            "gData_geometryData" => $this->gData_geometryData,
            "gData_code" => $this->gData_code,
            "gData_setPressurePsig" => $this->gData_setPressurePsig,
            "gData_reliefingTemperatureF" => $this->gData_reliefingTemperatureF,
            "gData_allowableOverPress" => $this->gData_allowableOverPress,
            "gData_designPressureBar" => $this->gData_designPressureBar,
            "gData_designPressurePsi" => $this->gData_designPressurePsi,
            "gData_designTemperatureC" => $this->gData_designTemperatureC,
            "gData_designTemperatureR" => $this->gData_designTemperatureR,
            "gData_designTemperatureF" => $this->gData_designTemperatureF,
            "gData_designTemperatureK" => $this->gData_designTemperatureK,
            "gData_operatingPressureBar" => $this->gData_operatingPressureBar,
            "gData_operatingPressurePsi" => $this->gData_operatingPressurePsi,
            "gData_operatingTemperatureC" => $this->gData_operatingTemperatureC,
            "gData_operatingTemperatureR" => $this->gData_operatingTemperatureR,
            "gData_operatingTemperatureF" => $this->gData_operatingTemperatureF,
            "gData_operatingTemperatureK" => $this->gData_operatingTemperatureK,
            "gData_dimmension" => $this->gData_dimmension,
            "gData_vesselVolumeLB" => $this->gData_vesselVolumeLB,
            "gData_vesselVolumeKG" => $this->gData_vesselVolumeKG,
            "gData_support" => $this->gData_support,
            "gData_jointEfficiency" => $this->gData_jointEfficiency,
            "gData_yieldStrength" => $this->gData_yieldStrength,
            "gData_tensileStrength" => $this->gData_tensileStrength,
            "gData_corrosionAllowanceMM" => $this->gData_corrosionAllowanceMM,
            "gData_corrosionAllowanceInch" => $this->gData_corrosionAllowanceInch,
            "gData_yearBuilt" => $this->gData_yearBuilt,
            "gData_material" => $this->gData_material,
            "gData_lastInspection" => $this->gData_lastInspection,
            "gData_nominalThicknessMM" => $this->gData_nominalThicknessMM,
            "gData_thickAfterInspMM" => $this->gData_thickAfterInspMM,
            "gData_outerDiameterMM" => $this->gData_outerDiameterMM,
            "gData_outerDiameterInch" => $this->gData_outerDiameterInch,
            "gData_allowableStressPsig" => $this->gData_allowableStressPsig,
            "gData_allowableStressBar" => $this->gData_allowableStressBar,
            "gData_allowableStressKpa" => $this->gData_allowableStressKpa,
            "gData_efficiency" => $this->gData_efficiency,
            "gData_shellCode" => $this->gData_shellCode,
            "gData_shellMinimumThicknessMM" => $this->gData_shellMinimumThicknessMM,
            "gData_shellMinimumThicknessInch" => $this->gData_shellMinimumThicknessInch,
            "gData_shellCorrosionRateMM" => $this->gData_shellCorrosionRateMM,
            "gData_shellCorrosionRateInch" => $this->gData_shellCorrosionRateInch,
            "gData_shellTreqInch" => $this->gData_shellTreqInch,
            "gData_shellTreqMM" => $this->gData_shellTreqMM,
            "gData_shellMAWP" => $this->gData_shellMAWP,
            "gData_headCode" => $this->gData_headCode,
            "gData_headMinimumThicknessMM" => $this->gData_headMinimumThicknessMM,
            "gData_headMinimumThicknessInch" => $this->gData_headMinimumThicknessInch,
            "gData_headCorrosionRateMM" => $this->gData_headCorrosionRateMM,
            "gData_headCorrosionRateInch" => $this->gData_headCorrosionRateInch,
            "gData_headTreqInch" => $this->gData_headTreqInch,
            "gData_headTreqMM" => $this->gData_headTreqMM,
            "gData_headMAWP" => $this->gData_headMAWP,
        ];
    }
}
