<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GeneralData extends Model
{
    use HasFactory;
    public $timestamps = true;
    protected $fillable = [
        "gData_id",
        "gData_componentId",
        "gData_tagNumber",
        "gData_startingDate",
        "gData_service",
        "gData_manufacturedBy",
        "gData_positionType",
        "gData_shapeType",
        "gData_geometryData",
        "gData_code",
        "gData_setPressurePsig",
        "gData_reliefingTemperatureF",
        "gData_allowableOverPress",
        "gData_designPressureBar",
        "gData_designPressurePsi",
        "gData_designTemperatureC",
        "gData_designTemperatureR",
        "gData_designTemperatureF",
        "gData_designTemperatureK",
        "gData_operatingPressureBar",
        "gData_operatingPressurePsi",
        "gData_operatingTemperatureC",
        "gData_operatingTemperatureR",
        "gData_operatingTemperatureF",
        "gData_operatingTemperatureK",
        "gData_dimensionLength",
        "gData_dimensionWidth",
        "gData_vesselVolumeLB",
        "gData_vesselVolumeKG",
        "gData_support",
        "gData_jointEfficiency",
        "gData_yieldStrength",
        "gData_tensileStrength",
        "gData_corrosionAllowanceMM",
        "gData_corrosionAllowanceInch",
        "gData_yearBuilt",
        "gData_material",
        "gData_lastInspection",
        "gData_nominalThicknessMM",
        "gData_thickAfterInspMM",
        "gData_outerDiameterMM",
        "gData_outerDiameterInch",
        "gData_allowableStressPsig",
        "gData_allowableStressBar",
        "gData_allowableStressKpa",
        "gData_efficiency",
        "gData_shellCode",
        "gData_shellMinimumThicknessMM",
        "gData_shellMinimumThicknessInch",
        "gData_shellCorrosionRateMM",
        "gData_shellCorrosionRateInch",
        "gData_shellTreqInch",
        "gData_shellTreqMM",
        "gData_shellMAWP",
        "gData_headCode",
        "gData_headMinimumThicknessMM",
        "gData_headMinimumThicknessInch",
        "gData_headCorrosionRateMM",
        "gData_headCorrosionRateInch",
        "gData_headTreqInch",
        "gData_headTreqMM",
        "gData_headMAWP",
    ];
}
